### ISSUE TITLE
连接详情内的 `dnsMod` 获取方式需要更改

### ISSUE THREAD

**Issue by DustinWin** [MetaCubeX/metacubexd#1282]
**地址：** 面板 -> 连接 -> 详情  
**说明：**  
自从 `fake-ip-filter` [引入域名集合](https://wiki.metacubex.one/handbook/syntax/#_13)（支持 `rule-set` 和 `geosite`）后，在通过如下配置（节选）
```
dns:
  enhanced-mode: fake-ip
  fake-ip-filter:
    - rule-set:cn
```
来模拟 mix 模式（即国内域名走 `redir-host`，国外域名走 `fake-ip`） 时，在面板内查看国内域名的连接详情，里面的 `dnsMod` 仍显示 `fake-ip`，此处应该显示 `redir-host`。所以 `dnsMod` 似乎是直接获取的 `enhanced-mode` 的值  
<img src="https://github.com/user-attachments/assets/a07005aa-5ba3-4928-9496-11477f78e919" width=60% />

希望 `dnsMod` 能根据实际情况获取当前域名的 dns 模式
