### ISSUE TITLE
empty proxy group selector that contains other proxy group or keyword

### ISSUE THREAD

**Issue by lux5am** [MetaCubeX/metacubexd#305]
```yaml
  - name: 🗿QUIC
    type: select
    proxies: 
      - REJECT
      - PASS
 ```
picrel empty expanded section.

![Screenshot_20230927-100604_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/7d6238bd-97af-4967-a244-64ac4bd19623)
![Screenshot_20230927-100617_Kiwi Browser](https://github.com/MetaCubeX/metacubexd/assets/110870661/24e25672-99ba-4ac2-9640-e1e9b507d263)
