### ISSUE TITLE
[BUG] 隐藏不可用的节点开启时 会将策略组中未测速的策略组隐藏

### ISSUE THREAD

**Issue by ObcbO** [MetaCubeX/metacubexd#322]
## 目前状况

![IMG_20231001_202514](https://github.com/MetaCubeX/metacubexd/assets/49872497/c1b1ce4b-011d-42c7-b1f6-fbc22ad3c8d2)

#### 图示配置文件(节选)

```yaml
proxy-groups:
  - name: 🚀 国外流量
    type: select
    proxies:
        - ♻️ 自动选择
        - 🔰 手动选择
        - 🌐 全球直连
        - 🚫 全球屏蔽
        - ⚖️ 负载均衡-散列
        - ⚖️ 负载均衡-轮询
```

## 期待结果

`隐藏不可用的节点` 开启时, 策略组中引用的另外一个策略组就没必要隐藏了, 也就是只隐藏不可用的节点, 而不是策略组
