### ISSUE TITLE
右侧纵向滚动条重叠问题

### ISSUE THREAD

**Issue by gg4924** [MetaCubeX/metacubexd#480]
右侧有两个滚动条重叠，使用鼠标拖动不便。另外在连接显示界面，横向滚动条会随着连接数变化跑出页面。
我目前通过如下改动临时解决了问题，希望能更稳妥的解决。
```html
<div class="pb-8 h-full overflow-y-auto">
```
```css
.pb-8 ::-webkit-scrollbar{display:block}
```
