### ISSUE TITLE
对proxy-groups中hidden参数的处理

### ISSUE THREAD

**Issue by Suyknow** [MetaCubeX/metacubexd#639]
根据[Clash Meta的Wiki](https://wiki.metacubex.one/en/config/proxy-groups/)
```
proxy-groups:
- name: "proxy"
  type: select
  proxies:
  - DIRECT
  - ss
  use:
  - provider1
  - provider1

  url: 'https://www.gstatic.com/generate_204'
  interval: 300
  lazy: true
  timeout: 5000

  disable-udp: true
  interface-name: en0
  routing-mark: 11451
  include-all: false
  include-all-proxies: false
  include-all-providers: false
  filter: "(?i)港|hk|hongkong|hong kong"
  exclude-filter: "美|日"
  exclude-type: "Shadowsocks|Http"
  expected-status: 204
  hidden: true
  icon: xxx
```

其中对hidden的说明如下：
[hidden](https://wiki.metacubex.one/en/config/proxy-groups/#hidden)[¶](https://wiki.metacubex.one/en/config/proxy-groups/#hidden)

Returns hidden status in the API to hide the display of this proxy-groups (requires front-end adaptation using the API).

目前MetaCube XD 似乎并不支持对hidden参数的处理，添加该参数后，面板仍然显示对应的Proxy Group
